schemaVersion: 2.2.0
attributes:
  controller.devfile.io/storage-type: per-workspace
metadata:
  name: quarkus-demo
components:
- name: dev-tools
  container: 
    image: image-registry.openshift-image-registry.svc:5000/eclipse-che-images/quarkus:latest
    memoryLimit: 6Gi
    mountSources: true
    volumeMounts:
    - name: m2
      path: /home/user/.m2
- container:
    args:
      - '-f'
      - /dev/null
    command:
      - tail
    env:
      - name: CHE_DASHBOARD_URL
        value: 'https://eclipse-che.apps.okd4-region-01.dc1.clg.lab'
      - name: CHE_PLUGIN_REGISTRY_URL
        value: 'https://eclipse-che.apps.okd4-region-01.dc1.clg.lab/plugin-registry/v3'
      - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
        value: 'http://plugin-registry.eclipse-che.svc:8080/v3'
      - name: OPENVSX_REGISTRY_URL
        value: ''
    image: registry.access.redhat.com/ubi9/ubi-minimal
    memoryLimit: 64M
    mountSources: true
    sourceMapping: /projects
  name: quarkus-native-runner
- volume:
    size: 4Gi
  name: projects
- volume:
    size: 2Gi
  name: m2
commands:
- exec:
    commandLine: mvn package
    component: dev-tools
    group:
      isDefault: true
      kind: build
    workingDir: '${PROJECT_SOURCE}'
  id: package
- exec:
    commandLine: mvn package -Dnative -Dmaven.test.skip -Dquarkus.native.native-image-xmx=2G
    component: dev-tools
    group:
      kind: build
    label: Package Native
    workingDir: '${PROJECT_SOURCE}'
  id: package-native
- exec:
    commandLine: 'mvn compile quarkus:dev'
    component: dev-tools
    group:
      isDefault: true
      kind: run
    label: Start Development mode (Hot reload + debug)
    workingDir: '${PROJECT_SOURCE}'
  id: start-dev
- exec:
    commandLine: ./code-with-quarkus-1.0.0-SNAPSHOT-runner
    component: ubi-minimal
    group:
      kind: run
    label: Start Native
    workingDir: '${PROJECT_SOURCE}/target'
  id: start-native